[package]
name = "celeste"
version = "0.5.8"
edition = "2021"

[dependencies]
relm4 = { version = "0.6.2", features = ["libadwaita"] }
relm4-components = "0.6.2"
relm4-icons = { version = "0.6.0", features = ["plus", "minus"] }